target:
  host: "myhost.com"
  user: "root"
  password: "mypassword"

gitlab:
  host: "gitlab.mydomain.com"
  user: "git"
  
git:
  user_name: "Gitlab"
  user_email: "gitlab@localhost"

postgresql:
  user: "git"
  password: "password"
  database: "gitlabhq_production"

packages:
  - "apt_update"
  - "build_essentials"
  - "python_software_properties"
  - "git"
  - "python"
  - "python_docutils"
  - "redis"
  - "postgresql"
  - "nginx"
  - "ruby"
  - "rubygems"
  - "bundler"
  - "gitlab"