target:
  host: "myhost.com"
  user: "root"
  password: "mypassword"

gitlab:
  host: "gitlab.mydomain.com"
  user: "git"
  
git:
  user_name: "Gitlab"
  user_email: "gitlab@localhost"
  core_autocrlf: "input"

postgresql:
  user: "git"
  password: "password"